title : Hvala za vse ribe
tagline: Hvala za vso podporo
description: Hvala za vse ribe je podporna spletna stran podkasta o knjigi Štoparski vodnik po Galaksiji. Podkast se imenuje Opravičujemo se za vse nevšečnosti in ga ustvarjamo Aljo, Peli in Zi. 
author :
  name : Davorin Pavlica
  email : davorin.pavlica@zvpl.com
  github : davorinpavlica
  twitter : davorinpavlica
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: opravicujemose
google_analytics: UA-686717-20

plugins:
  - jekyll-redirect-from